### ISSUE TITLE
domains file :i could not find domains file

### ISSUE THREAD

**Issue by lancy-liang** [salzmanlab/SICILIAN#22]
i want to download domains file about sus scrofa11.1,but i could not find that

**Comment by lancy-liang** [comment]
Traceback (most recent call last):
  File "new_SICILIAN.py", line 235, in <module>
    main()
  File "new_SICILIAN.py", line 229, in main
    GLM_jobid = GLM(out_path, name, gtf_file, single, tenX, stranded_library, domain_file, exon_pickle_file, splice_pickle_file, dep=":".join(job_nums))
NameError: name 'domain_file' is not defined
